import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>FluidSenses Resume</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className=''>
          WEBSITE IS UNDER CONSTRUCTION
      </main>
    </>
  )
}
